/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    CoffeeTracker: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "admin",
              type: "address",
            },
            {
              internalType: "address",
              name: "farmer",
              type: "address",
            },
            {
              internalType: "address",
              name: "processor",
              type: "address",
            },
            {
              internalType: "address",
              name: "roaster",
              type: "address",
            },
            {
              internalType: "address",
              name: "distributor",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "AccessControlBadConfirmation",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "neededRole",
              type: "bytes32",
            },
          ],
          name: "AccessControlUnauthorizedAccount",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "sender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "balance",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "needed",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "ERC1155InsufficientBalance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "approver",
              type: "address",
            },
          ],
          name: "ERC1155InvalidApprover",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "idsLength",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "valuesLength",
              type: "uint256",
            },
          ],
          name: "ERC1155InvalidArrayLength",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
          ],
          name: "ERC1155InvalidOperator",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "receiver",
              type: "address",
            },
          ],
          name: "ERC1155InvalidReceiver",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "sender",
              type: "address",
            },
          ],
          name: "ERC1155InvalidSender",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "ERC1155MissingApprovalForAll",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "ApprovalForAll",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "batchId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint32",
              name: "distributionDate",
              type: "uint32",
            },
            {
              indexed: false,
              internalType: "uint32",
              name: "bagCount",
              type: "uint32",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "distributionWeight",
              type: "uint64",
            },
            {
              indexed: true,
              internalType: "address",
              name: "distributor",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "destination",
              type: "string",
            },
            {
              indexed: false,
              internalType: "int32",
              name: "latitude",
              type: "int32",
            },
            {
              indexed: false,
              internalType: "int32",
              name: "longitude",
              type: "int32",
            },
          ],
          name: "Distributed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "batchId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "batchNumber",
              type: "string",
            },
            {
              indexed: false,
              internalType: "enum CoffeeTracker.Region",
              name: "region",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "enum CoffeeTracker.Variety",
              name: "variety",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint16",
              name: "elevation",
              type: "uint16",
            },
            {
              indexed: false,
              internalType: "uint32",
              name: "harvestDate",
              type: "uint32",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "harvestWeight",
              type: "uint64",
            },
            {
              indexed: true,
              internalType: "address",
              name: "farmer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "farmName",
              type: "string",
            },
            {
              indexed: false,
              internalType: "int32",
              name: "latitude",
              type: "int32",
            },
            {
              indexed: false,
              internalType: "int32",
              name: "longitude",
              type: "int32",
            },
          ],
          name: "Harvested",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "batchId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "enum CoffeeTracker.ProcessingMethod",
              name: "processingMethod",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "moistureContent",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "scaScore",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "humidity",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint16",
              name: "dryTemperature",
              type: "uint16",
            },
            {
              indexed: false,
              internalType: "uint32",
              name: "processingDate",
              type: "uint32",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "beforeWeight",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "afterWeight",
              type: "uint64",
            },
            {
              indexed: true,
              internalType: "address",
              name: "processor",
              type: "address",
            },
            {
              indexed: false,
              internalType: "int32",
              name: "latitude",
              type: "int32",
            },
            {
              indexed: false,
              internalType: "int32",
              name: "longitude",
              type: "int32",
            },
          ],
          name: "Processed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "batchId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "enum CoffeeTracker.RoastingMethod",
              name: "roastingMethod",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "enum CoffeeTracker.RoastLevel",
              name: "roastLevel",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint16",
              name: "transportTime",
              type: "uint16",
            },
            {
              indexed: false,
              internalType: "uint32",
              name: "roastingDate",
              type: "uint32",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "beforeWeight",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "afterWeight",
              type: "uint64",
            },
            {
              indexed: true,
              internalType: "address",
              name: "roaster",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "cuppingNotes",
              type: "string",
            },
            {
              indexed: false,
              internalType: "int32",
              name: "latitude",
              type: "int32",
            },
            {
              indexed: false,
              internalType: "int32",
              name: "longitude",
              type: "int32",
            },
          ],
          name: "Roasted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "previousAdminRole",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "newAdminRole",
              type: "bytes32",
            },
          ],
          name: "RoleAdminChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "sender",
              type: "address",
            },
          ],
          name: "RoleGranted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "sender",
              type: "address",
            },
          ],
          name: "RoleRevoked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256[]",
              name: "ids",
              type: "uint256[]",
            },
            {
              indexed: false,
              internalType: "uint256[]",
              name: "values",
              type: "uint256[]",
            },
          ],
          name: "TransferBatch",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "TransferSingle",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "value",
              type: "string",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "URI",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "batchId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "verifier",
              type: "address",
            },
          ],
          name: "Verified",
          type: "event",
        },
        {
          inputs: [],
          name: "DEFAULT_ADMIN_ROLE",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "DISTRIBUTOR_ROLE",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "FARMER_ROLE",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "PROCESSOR_ROLE",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "ROASTER_ROLE",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "accounts",
              type: "address[]",
            },
            {
              internalType: "uint256[]",
              name: "ids",
              type: "uint256[]",
            },
          ],
          name: "balanceOfBatch",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          name: "batchNumberToId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_batchId",
              type: "uint256",
            },
            {
              internalType: "uint32",
              name: "_distributionDate",
              type: "uint32",
            },
            {
              internalType: "uint32",
              name: "_bagCount",
              type: "uint32",
            },
            {
              internalType: "uint64",
              name: "_distributionWeight",
              type: "uint64",
            },
            {
              internalType: "string",
              name: "_destination",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "int32",
                  name: "latitude",
                  type: "int32",
                },
                {
                  internalType: "int32",
                  name: "longitude",
                  type: "int32",
                },
              ],
              internalType: "struct CoffeeTracker.Coordinates",
              name: "_location",
              type: "tuple",
            },
          ],
          name: "distributeBatch",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_batchId",
              type: "uint256",
            },
          ],
          name: "getBatch",
          outputs: [
            {
              components: [
                {
                  internalType: "uint64",
                  name: "batchId",
                  type: "uint64",
                },
                {
                  internalType: "string",
                  name: "batchNumber",
                  type: "string",
                },
                {
                  components: [
                    {
                      internalType: "enum CoffeeTracker.Region",
                      name: "region",
                      type: "uint8",
                    },
                    {
                      internalType: "enum CoffeeTracker.Variety",
                      name: "variety",
                      type: "uint8",
                    },
                    {
                      internalType: "uint16",
                      name: "elevation",
                      type: "uint16",
                    },
                    {
                      internalType: "uint32",
                      name: "harvestDate",
                      type: "uint32",
                    },
                    {
                      internalType: "uint64",
                      name: "harvestWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "address",
                      name: "farmer",
                      type: "address",
                    },
                    {
                      internalType: "string",
                      name: "farmName",
                      type: "string",
                    },
                    {
                      components: [
                        {
                          internalType: "int32",
                          name: "latitude",
                          type: "int32",
                        },
                        {
                          internalType: "int32",
                          name: "longitude",
                          type: "int32",
                        },
                      ],
                      internalType: "struct CoffeeTracker.Coordinates",
                      name: "location",
                      type: "tuple",
                    },
                  ],
                  internalType: "struct CoffeeTracker.HarvestData",
                  name: "harvestData",
                  type: "tuple",
                },
                {
                  components: [
                    {
                      internalType: "enum CoffeeTracker.ProcessingMethod",
                      name: "processingMethod",
                      type: "uint8",
                    },
                    {
                      internalType: "uint8",
                      name: "moistureContent",
                      type: "uint8",
                    },
                    {
                      internalType: "uint8",
                      name: "scaScore",
                      type: "uint8",
                    },
                    {
                      internalType: "uint8",
                      name: "humidity",
                      type: "uint8",
                    },
                    {
                      internalType: "uint16",
                      name: "dryTemperature",
                      type: "uint16",
                    },
                    {
                      internalType: "uint32",
                      name: "processingDate",
                      type: "uint32",
                    },
                    {
                      internalType: "uint64",
                      name: "beforeWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "uint64",
                      name: "afterWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "address",
                      name: "processor",
                      type: "address",
                    },
                    {
                      components: [
                        {
                          internalType: "int32",
                          name: "latitude",
                          type: "int32",
                        },
                        {
                          internalType: "int32",
                          name: "longitude",
                          type: "int32",
                        },
                      ],
                      internalType: "struct CoffeeTracker.Coordinates",
                      name: "location",
                      type: "tuple",
                    },
                  ],
                  internalType: "struct CoffeeTracker.ProcessingData",
                  name: "processingData",
                  type: "tuple",
                },
                {
                  components: [
                    {
                      internalType: "enum CoffeeTracker.RoastingMethod",
                      name: "roastingMethod",
                      type: "uint8",
                    },
                    {
                      internalType: "enum CoffeeTracker.RoastLevel",
                      name: "roastLevel",
                      type: "uint8",
                    },
                    {
                      internalType: "uint16",
                      name: "transportTime",
                      type: "uint16",
                    },
                    {
                      internalType: "uint32",
                      name: "roastingDate",
                      type: "uint32",
                    },
                    {
                      internalType: "uint64",
                      name: "beforeWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "uint64",
                      name: "afterWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "address",
                      name: "roaster",
                      type: "address",
                    },
                    {
                      internalType: "string",
                      name: "cuppingNotes",
                      type: "string",
                    },
                    {
                      components: [
                        {
                          internalType: "int32",
                          name: "latitude",
                          type: "int32",
                        },
                        {
                          internalType: "int32",
                          name: "longitude",
                          type: "int32",
                        },
                      ],
                      internalType: "struct CoffeeTracker.Coordinates",
                      name: "location",
                      type: "tuple",
                    },
                  ],
                  internalType: "struct CoffeeTracker.RoastingData",
                  name: "roastingData",
                  type: "tuple",
                },
                {
                  components: [
                    {
                      internalType: "uint32",
                      name: "distributionDate",
                      type: "uint32",
                    },
                    {
                      internalType: "uint32",
                      name: "bagCount",
                      type: "uint32",
                    },
                    {
                      internalType: "uint64",
                      name: "distributionWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "address",
                      name: "distributor",
                      type: "address",
                    },
                    {
                      internalType: "string",
                      name: "destination",
                      type: "string",
                    },
                    {
                      components: [
                        {
                          internalType: "int32",
                          name: "latitude",
                          type: "int32",
                        },
                        {
                          internalType: "int32",
                          name: "longitude",
                          type: "int32",
                        },
                      ],
                      internalType: "struct CoffeeTracker.Coordinates",
                      name: "location",
                      type: "tuple",
                    },
                  ],
                  internalType: "struct CoffeeTracker.DistributionData",
                  name: "distributionData",
                  type: "tuple",
                },
                {
                  internalType: "bool",
                  name: "verified",
                  type: "bool",
                },
                {
                  internalType: "uint32",
                  name: "mintTimestamp",
                  type: "uint32",
                },
              ],
              internalType: "struct CoffeeTracker.CoffeeBatch",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_batchNumber",
              type: "string",
            },
          ],
          name: "getBatchByNumber",
          outputs: [
            {
              components: [
                {
                  internalType: "uint64",
                  name: "batchId",
                  type: "uint64",
                },
                {
                  internalType: "string",
                  name: "batchNumber",
                  type: "string",
                },
                {
                  components: [
                    {
                      internalType: "enum CoffeeTracker.Region",
                      name: "region",
                      type: "uint8",
                    },
                    {
                      internalType: "enum CoffeeTracker.Variety",
                      name: "variety",
                      type: "uint8",
                    },
                    {
                      internalType: "uint16",
                      name: "elevation",
                      type: "uint16",
                    },
                    {
                      internalType: "uint32",
                      name: "harvestDate",
                      type: "uint32",
                    },
                    {
                      internalType: "uint64",
                      name: "harvestWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "address",
                      name: "farmer",
                      type: "address",
                    },
                    {
                      internalType: "string",
                      name: "farmName",
                      type: "string",
                    },
                    {
                      components: [
                        {
                          internalType: "int32",
                          name: "latitude",
                          type: "int32",
                        },
                        {
                          internalType: "int32",
                          name: "longitude",
                          type: "int32",
                        },
                      ],
                      internalType: "struct CoffeeTracker.Coordinates",
                      name: "location",
                      type: "tuple",
                    },
                  ],
                  internalType: "struct CoffeeTracker.HarvestData",
                  name: "harvestData",
                  type: "tuple",
                },
                {
                  components: [
                    {
                      internalType: "enum CoffeeTracker.ProcessingMethod",
                      name: "processingMethod",
                      type: "uint8",
                    },
                    {
                      internalType: "uint8",
                      name: "moistureContent",
                      type: "uint8",
                    },
                    {
                      internalType: "uint8",
                      name: "scaScore",
                      type: "uint8",
                    },
                    {
                      internalType: "uint8",
                      name: "humidity",
                      type: "uint8",
                    },
                    {
                      internalType: "uint16",
                      name: "dryTemperature",
                      type: "uint16",
                    },
                    {
                      internalType: "uint32",
                      name: "processingDate",
                      type: "uint32",
                    },
                    {
                      internalType: "uint64",
                      name: "beforeWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "uint64",
                      name: "afterWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "address",
                      name: "processor",
                      type: "address",
                    },
                    {
                      components: [
                        {
                          internalType: "int32",
                          name: "latitude",
                          type: "int32",
                        },
                        {
                          internalType: "int32",
                          name: "longitude",
                          type: "int32",
                        },
                      ],
                      internalType: "struct CoffeeTracker.Coordinates",
                      name: "location",
                      type: "tuple",
                    },
                  ],
                  internalType: "struct CoffeeTracker.ProcessingData",
                  name: "processingData",
                  type: "tuple",
                },
                {
                  components: [
                    {
                      internalType: "enum CoffeeTracker.RoastingMethod",
                      name: "roastingMethod",
                      type: "uint8",
                    },
                    {
                      internalType: "enum CoffeeTracker.RoastLevel",
                      name: "roastLevel",
                      type: "uint8",
                    },
                    {
                      internalType: "uint16",
                      name: "transportTime",
                      type: "uint16",
                    },
                    {
                      internalType: "uint32",
                      name: "roastingDate",
                      type: "uint32",
                    },
                    {
                      internalType: "uint64",
                      name: "beforeWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "uint64",
                      name: "afterWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "address",
                      name: "roaster",
                      type: "address",
                    },
                    {
                      internalType: "string",
                      name: "cuppingNotes",
                      type: "string",
                    },
                    {
                      components: [
                        {
                          internalType: "int32",
                          name: "latitude",
                          type: "int32",
                        },
                        {
                          internalType: "int32",
                          name: "longitude",
                          type: "int32",
                        },
                      ],
                      internalType: "struct CoffeeTracker.Coordinates",
                      name: "location",
                      type: "tuple",
                    },
                  ],
                  internalType: "struct CoffeeTracker.RoastingData",
                  name: "roastingData",
                  type: "tuple",
                },
                {
                  components: [
                    {
                      internalType: "uint32",
                      name: "distributionDate",
                      type: "uint32",
                    },
                    {
                      internalType: "uint32",
                      name: "bagCount",
                      type: "uint32",
                    },
                    {
                      internalType: "uint64",
                      name: "distributionWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "address",
                      name: "distributor",
                      type: "address",
                    },
                    {
                      internalType: "string",
                      name: "destination",
                      type: "string",
                    },
                    {
                      components: [
                        {
                          internalType: "int32",
                          name: "latitude",
                          type: "int32",
                        },
                        {
                          internalType: "int32",
                          name: "longitude",
                          type: "int32",
                        },
                      ],
                      internalType: "struct CoffeeTracker.Coordinates",
                      name: "location",
                      type: "tuple",
                    },
                  ],
                  internalType: "struct CoffeeTracker.DistributionData",
                  name: "distributionData",
                  type: "tuple",
                },
                {
                  internalType: "bool",
                  name: "verified",
                  type: "bool",
                },
                {
                  internalType: "uint32",
                  name: "mintTimestamp",
                  type: "uint32",
                },
              ],
              internalType: "struct CoffeeTracker.CoffeeBatch",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getBatchCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "offset",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "limit",
              type: "uint256",
            },
          ],
          name: "getBatches",
          outputs: [
            {
              components: [
                {
                  internalType: "uint64",
                  name: "batchId",
                  type: "uint64",
                },
                {
                  internalType: "string",
                  name: "batchNumber",
                  type: "string",
                },
                {
                  components: [
                    {
                      internalType: "enum CoffeeTracker.Region",
                      name: "region",
                      type: "uint8",
                    },
                    {
                      internalType: "enum CoffeeTracker.Variety",
                      name: "variety",
                      type: "uint8",
                    },
                    {
                      internalType: "uint16",
                      name: "elevation",
                      type: "uint16",
                    },
                    {
                      internalType: "uint32",
                      name: "harvestDate",
                      type: "uint32",
                    },
                    {
                      internalType: "uint64",
                      name: "harvestWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "address",
                      name: "farmer",
                      type: "address",
                    },
                    {
                      internalType: "string",
                      name: "farmName",
                      type: "string",
                    },
                    {
                      components: [
                        {
                          internalType: "int32",
                          name: "latitude",
                          type: "int32",
                        },
                        {
                          internalType: "int32",
                          name: "longitude",
                          type: "int32",
                        },
                      ],
                      internalType: "struct CoffeeTracker.Coordinates",
                      name: "location",
                      type: "tuple",
                    },
                  ],
                  internalType: "struct CoffeeTracker.HarvestData",
                  name: "harvestData",
                  type: "tuple",
                },
                {
                  components: [
                    {
                      internalType: "enum CoffeeTracker.ProcessingMethod",
                      name: "processingMethod",
                      type: "uint8",
                    },
                    {
                      internalType: "uint8",
                      name: "moistureContent",
                      type: "uint8",
                    },
                    {
                      internalType: "uint8",
                      name: "scaScore",
                      type: "uint8",
                    },
                    {
                      internalType: "uint8",
                      name: "humidity",
                      type: "uint8",
                    },
                    {
                      internalType: "uint16",
                      name: "dryTemperature",
                      type: "uint16",
                    },
                    {
                      internalType: "uint32",
                      name: "processingDate",
                      type: "uint32",
                    },
                    {
                      internalType: "uint64",
                      name: "beforeWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "uint64",
                      name: "afterWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "address",
                      name: "processor",
                      type: "address",
                    },
                    {
                      components: [
                        {
                          internalType: "int32",
                          name: "latitude",
                          type: "int32",
                        },
                        {
                          internalType: "int32",
                          name: "longitude",
                          type: "int32",
                        },
                      ],
                      internalType: "struct CoffeeTracker.Coordinates",
                      name: "location",
                      type: "tuple",
                    },
                  ],
                  internalType: "struct CoffeeTracker.ProcessingData",
                  name: "processingData",
                  type: "tuple",
                },
                {
                  components: [
                    {
                      internalType: "enum CoffeeTracker.RoastingMethod",
                      name: "roastingMethod",
                      type: "uint8",
                    },
                    {
                      internalType: "enum CoffeeTracker.RoastLevel",
                      name: "roastLevel",
                      type: "uint8",
                    },
                    {
                      internalType: "uint16",
                      name: "transportTime",
                      type: "uint16",
                    },
                    {
                      internalType: "uint32",
                      name: "roastingDate",
                      type: "uint32",
                    },
                    {
                      internalType: "uint64",
                      name: "beforeWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "uint64",
                      name: "afterWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "address",
                      name: "roaster",
                      type: "address",
                    },
                    {
                      internalType: "string",
                      name: "cuppingNotes",
                      type: "string",
                    },
                    {
                      components: [
                        {
                          internalType: "int32",
                          name: "latitude",
                          type: "int32",
                        },
                        {
                          internalType: "int32",
                          name: "longitude",
                          type: "int32",
                        },
                      ],
                      internalType: "struct CoffeeTracker.Coordinates",
                      name: "location",
                      type: "tuple",
                    },
                  ],
                  internalType: "struct CoffeeTracker.RoastingData",
                  name: "roastingData",
                  type: "tuple",
                },
                {
                  components: [
                    {
                      internalType: "uint32",
                      name: "distributionDate",
                      type: "uint32",
                    },
                    {
                      internalType: "uint32",
                      name: "bagCount",
                      type: "uint32",
                    },
                    {
                      internalType: "uint64",
                      name: "distributionWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "address",
                      name: "distributor",
                      type: "address",
                    },
                    {
                      internalType: "string",
                      name: "destination",
                      type: "string",
                    },
                    {
                      components: [
                        {
                          internalType: "int32",
                          name: "latitude",
                          type: "int32",
                        },
                        {
                          internalType: "int32",
                          name: "longitude",
                          type: "int32",
                        },
                      ],
                      internalType: "struct CoffeeTracker.Coordinates",
                      name: "location",
                      type: "tuple",
                    },
                  ],
                  internalType: "struct CoffeeTracker.DistributionData",
                  name: "distributionData",
                  type: "tuple",
                },
                {
                  internalType: "bool",
                  name: "verified",
                  type: "bool",
                },
                {
                  internalType: "uint32",
                  name: "mintTimestamp",
                  type: "uint32",
                },
              ],
              internalType: "struct CoffeeTracker.CoffeeBatch[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getFarmCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "getRole",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
          ],
          name: "getRoleAdmin",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getTransactionCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "getUserBatches",
          outputs: [
            {
              internalType: "string",
              name: "userRole",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "uint64",
                  name: "batchId",
                  type: "uint64",
                },
                {
                  internalType: "string",
                  name: "batchNumber",
                  type: "string",
                },
                {
                  components: [
                    {
                      internalType: "enum CoffeeTracker.Region",
                      name: "region",
                      type: "uint8",
                    },
                    {
                      internalType: "enum CoffeeTracker.Variety",
                      name: "variety",
                      type: "uint8",
                    },
                    {
                      internalType: "uint16",
                      name: "elevation",
                      type: "uint16",
                    },
                    {
                      internalType: "uint32",
                      name: "harvestDate",
                      type: "uint32",
                    },
                    {
                      internalType: "uint64",
                      name: "harvestWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "address",
                      name: "farmer",
                      type: "address",
                    },
                    {
                      internalType: "string",
                      name: "farmName",
                      type: "string",
                    },
                    {
                      components: [
                        {
                          internalType: "int32",
                          name: "latitude",
                          type: "int32",
                        },
                        {
                          internalType: "int32",
                          name: "longitude",
                          type: "int32",
                        },
                      ],
                      internalType: "struct CoffeeTracker.Coordinates",
                      name: "location",
                      type: "tuple",
                    },
                  ],
                  internalType: "struct CoffeeTracker.HarvestData",
                  name: "harvestData",
                  type: "tuple",
                },
                {
                  components: [
                    {
                      internalType: "enum CoffeeTracker.ProcessingMethod",
                      name: "processingMethod",
                      type: "uint8",
                    },
                    {
                      internalType: "uint8",
                      name: "moistureContent",
                      type: "uint8",
                    },
                    {
                      internalType: "uint8",
                      name: "scaScore",
                      type: "uint8",
                    },
                    {
                      internalType: "uint8",
                      name: "humidity",
                      type: "uint8",
                    },
                    {
                      internalType: "uint16",
                      name: "dryTemperature",
                      type: "uint16",
                    },
                    {
                      internalType: "uint32",
                      name: "processingDate",
                      type: "uint32",
                    },
                    {
                      internalType: "uint64",
                      name: "beforeWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "uint64",
                      name: "afterWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "address",
                      name: "processor",
                      type: "address",
                    },
                    {
                      components: [
                        {
                          internalType: "int32",
                          name: "latitude",
                          type: "int32",
                        },
                        {
                          internalType: "int32",
                          name: "longitude",
                          type: "int32",
                        },
                      ],
                      internalType: "struct CoffeeTracker.Coordinates",
                      name: "location",
                      type: "tuple",
                    },
                  ],
                  internalType: "struct CoffeeTracker.ProcessingData",
                  name: "processingData",
                  type: "tuple",
                },
                {
                  components: [
                    {
                      internalType: "enum CoffeeTracker.RoastingMethod",
                      name: "roastingMethod",
                      type: "uint8",
                    },
                    {
                      internalType: "enum CoffeeTracker.RoastLevel",
                      name: "roastLevel",
                      type: "uint8",
                    },
                    {
                      internalType: "uint16",
                      name: "transportTime",
                      type: "uint16",
                    },
                    {
                      internalType: "uint32",
                      name: "roastingDate",
                      type: "uint32",
                    },
                    {
                      internalType: "uint64",
                      name: "beforeWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "uint64",
                      name: "afterWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "address",
                      name: "roaster",
                      type: "address",
                    },
                    {
                      internalType: "string",
                      name: "cuppingNotes",
                      type: "string",
                    },
                    {
                      components: [
                        {
                          internalType: "int32",
                          name: "latitude",
                          type: "int32",
                        },
                        {
                          internalType: "int32",
                          name: "longitude",
                          type: "int32",
                        },
                      ],
                      internalType: "struct CoffeeTracker.Coordinates",
                      name: "location",
                      type: "tuple",
                    },
                  ],
                  internalType: "struct CoffeeTracker.RoastingData",
                  name: "roastingData",
                  type: "tuple",
                },
                {
                  components: [
                    {
                      internalType: "uint32",
                      name: "distributionDate",
                      type: "uint32",
                    },
                    {
                      internalType: "uint32",
                      name: "bagCount",
                      type: "uint32",
                    },
                    {
                      internalType: "uint64",
                      name: "distributionWeight",
                      type: "uint64",
                    },
                    {
                      internalType: "address",
                      name: "distributor",
                      type: "address",
                    },
                    {
                      internalType: "string",
                      name: "destination",
                      type: "string",
                    },
                    {
                      components: [
                        {
                          internalType: "int32",
                          name: "latitude",
                          type: "int32",
                        },
                        {
                          internalType: "int32",
                          name: "longitude",
                          type: "int32",
                        },
                      ],
                      internalType: "struct CoffeeTracker.Coordinates",
                      name: "location",
                      type: "tuple",
                    },
                  ],
                  internalType: "struct CoffeeTracker.DistributionData",
                  name: "distributionData",
                  type: "tuple",
                },
                {
                  internalType: "bool",
                  name: "verified",
                  type: "bool",
                },
                {
                  internalType: "uint32",
                  name: "mintTimestamp",
                  type: "uint32",
                },
              ],
              internalType: "struct CoffeeTracker.CoffeeBatch[]",
              name: "history",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "grantRole",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_batchNumber",
              type: "string",
            },
            {
              internalType: "enum CoffeeTracker.Region",
              name: "_region",
              type: "uint8",
            },
            {
              internalType: "enum CoffeeTracker.Variety",
              name: "_variety",
              type: "uint8",
            },
            {
              internalType: "uint16",
              name: "_elevation",
              type: "uint16",
            },
            {
              internalType: "uint32",
              name: "_harvestDate",
              type: "uint32",
            },
            {
              internalType: "uint64",
              name: "_harvestWeight",
              type: "uint64",
            },
            {
              internalType: "string",
              name: "_farmName",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "int32",
                  name: "latitude",
                  type: "int32",
                },
                {
                  internalType: "int32",
                  name: "longitude",
                  type: "int32",
                },
              ],
              internalType: "struct CoffeeTracker.Coordinates",
              name: "_location",
              type: "tuple",
            },
          ],
          name: "harvestBatch",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "hasRole",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
          ],
          name: "isApprovedForAll",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_batchId",
              type: "uint256",
            },
            {
              internalType: "enum CoffeeTracker.ProcessingMethod",
              name: "_processingMethod",
              type: "uint8",
            },
            {
              internalType: "uint8",
              name: "_moistureContent",
              type: "uint8",
            },
            {
              internalType: "uint8",
              name: "_scaScore",
              type: "uint8",
            },
            {
              internalType: "uint8",
              name: "_humidity",
              type: "uint8",
            },
            {
              internalType: "uint16",
              name: "_dryTemperature",
              type: "uint16",
            },
            {
              internalType: "uint32",
              name: "_processingDate",
              type: "uint32",
            },
            {
              internalType: "uint64",
              name: "_beforeWeight",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "_afterWeight",
              type: "uint64",
            },
            {
              components: [
                {
                  internalType: "int32",
                  name: "latitude",
                  type: "int32",
                },
                {
                  internalType: "int32",
                  name: "longitude",
                  type: "int32",
                },
              ],
              internalType: "struct CoffeeTracker.Coordinates",
              name: "_location",
              type: "tuple",
            },
          ],
          name: "processBatch",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "callerConfirmation",
              type: "address",
            },
          ],
          name: "renounceRole",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "revokeRole",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_batchId",
              type: "uint256",
            },
            {
              internalType: "enum CoffeeTracker.RoastingMethod",
              name: "_roastingMethod",
              type: "uint8",
            },
            {
              internalType: "enum CoffeeTracker.RoastLevel",
              name: "_roastLevel",
              type: "uint8",
            },
            {
              internalType: "uint16",
              name: "_transportTime",
              type: "uint16",
            },
            {
              internalType: "uint32",
              name: "_roastingDate",
              type: "uint32",
            },
            {
              internalType: "uint64",
              name: "_beforeWeight",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "_afterWeight",
              type: "uint64",
            },
            {
              internalType: "string",
              name: "_cuppingNotes",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "int32",
                  name: "latitude",
                  type: "int32",
                },
                {
                  internalType: "int32",
                  name: "longitude",
                  type: "int32",
                },
              ],
              internalType: "struct CoffeeTracker.Coordinates",
              name: "_location",
              type: "tuple",
            },
          ],
          name: "roastBatch",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256[]",
              name: "ids",
              type: "uint256[]",
            },
            {
              internalType: "uint256[]",
              name: "values",
              type: "uint256[]",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "safeBatchTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "safeTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "setApprovalForAll",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "interfaceId",
              type: "bytes4",
            },
          ],
          name: "supportsInterface",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "uri",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_batchId",
              type: "uint256",
            },
          ],
          name: "verifyBatch",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        balanceOf: "@openzeppelin/contracts/token/ERC1155/ERC1155.sol",
        balanceOfBatch: "@openzeppelin/contracts/token/ERC1155/ERC1155.sol",
        isApprovedForAll: "@openzeppelin/contracts/token/ERC1155/ERC1155.sol",
        safeBatchTransferFrom: "@openzeppelin/contracts/token/ERC1155/ERC1155.sol",
        safeTransferFrom: "@openzeppelin/contracts/token/ERC1155/ERC1155.sol",
        setApprovalForAll: "@openzeppelin/contracts/token/ERC1155/ERC1155.sol",
        supportsInterface: "@openzeppelin/contracts/access/AccessControl.sol",
        uri: "@openzeppelin/contracts/token/ERC1155/ERC1155.sol",
        DEFAULT_ADMIN_ROLE: "@openzeppelin/contracts/access/AccessControl.sol",
        getRoleAdmin: "@openzeppelin/contracts/access/AccessControl.sol",
        grantRole: "@openzeppelin/contracts/access/AccessControl.sol",
        hasRole: "@openzeppelin/contracts/access/AccessControl.sol",
        renounceRole: "@openzeppelin/contracts/access/AccessControl.sol",
        revokeRole: "@openzeppelin/contracts/access/AccessControl.sol",
      },
      deployedOnBlock: 1,
    },
  },
  84532: {
    CoffeeTracker: {
      address: "0xb293E5cd1836C62EDD273E56488b7a140D696F16",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "sender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "balance",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "needed",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "ERC1155InsufficientBalance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "approver",
              type: "address",
            },
          ],
          name: "ERC1155InvalidApprover",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "idsLength",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "valuesLength",
              type: "uint256",
            },
          ],
          name: "ERC1155InvalidArrayLength",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
          ],
          name: "ERC1155InvalidOperator",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "receiver",
              type: "address",
            },
          ],
          name: "ERC1155InvalidReceiver",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "sender",
              type: "address",
            },
          ],
          name: "ERC1155InvalidSender",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "ERC1155MissingApprovalForAll",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "ApprovalForAll",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "batchId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "farmName",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "region",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "variety",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "harvestDate",
              type: "uint256",
            },
          ],
          name: "Harvested",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256[]",
              name: "ids",
              type: "uint256[]",
            },
            {
              indexed: false,
              internalType: "uint256[]",
              name: "values",
              type: "uint256[]",
            },
          ],
          name: "TransferBatch",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "TransferSingle",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "value",
              type: "string",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "URI",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "accounts",
              type: "address[]",
            },
            {
              internalType: "uint256[]",
              name: "ids",
              type: "uint256[]",
            },
          ],
          name: "balanceOfBatch",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "batches",
          outputs: [
            {
              internalType: "string",
              name: "farmName",
              type: "string",
            },
            {
              internalType: "string",
              name: "region",
              type: "string",
            },
            {
              internalType: "string",
              name: "variety",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "harvestDate",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "currentBatchId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_farm",
              type: "string",
            },
            {
              internalType: "string",
              name: "_region",
              type: "string",
            },
            {
              internalType: "string",
              name: "_variety",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "_quantity",
              type: "uint256",
            },
          ],
          name: "harvestBatch",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
          ],
          name: "isApprovedForAll",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256[]",
              name: "ids",
              type: "uint256[]",
            },
            {
              internalType: "uint256[]",
              name: "values",
              type: "uint256[]",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "safeBatchTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "safeTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "setApprovalForAll",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "interfaceId",
              type: "bytes4",
            },
          ],
          name: "supportsInterface",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "uri",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 38080710,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
